using System.Runtime.InteropServices;
Console.Clear();

Console.BackgroundColor = ConsoleColor.Red;
Console.ForegroundColor = ConsoleColor.Black;
Console.Write("S");
Console.ForegroundColor = ConsoleColor.Red;
Console.BackgroundColor = ConsoleColor.White;
Console.Write("ã");
Console.ForegroundColor = ConsoleColor.Black;
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("o");
Console.ForegroundColor = ConsoleColor.Red;
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.ForegroundColor = ConsoleColor.Black;
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("P");
Console.ForegroundColor = ConsoleColor.Red;
Console.BackgroundColor = ConsoleColor.White;
Console.Write("a");
Console.ForegroundColor = ConsoleColor.Black;
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("u");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("l");
Console.ForegroundColor = ConsoleColor.Black;
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("o");
Console.ResetColor();
Console.WriteLine("");

Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("███████╗ █████╗  ██████╗     ██████╗  █████╗ ██╗   ██╗██╗      ██████╗ ");
Console.WriteLine("██╔════╝██╔══██╗██╔═══██╗    ██╔══██╗██╔══██╗██║   ██║██║     ██╔═══██╗");
Console.WriteLine("███████╗███████║██║   ██║    ██████╔╝███████║██║   ██║██║     ██║   ██║");
Console.WriteLine("╚════██║██╔══██║██║   ██║    ██╔═══╝ ██╔══██║██║   ██║██║     ██║   ██║");
Console.WriteLine("███████║██║  ██║╚██████╔╝    ██║     ██║  ██║╚██████╔╝███████╗╚██████╔╝");
Console.WriteLine("╚══════╝╚═╝  ╚═╝ ╚═════╝     ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝ ╚═════╝ ");
Console.ResetColor();